version: "3.9"
services:
  frontend:
    build:
      context: .
    ports:
      - "3000:80"
    env_file:
      - .env.local
    depends_on:
      - yjs

  yjs:
    build:
      context: ./server
    ports:
      - "1234:1234"