services:
  - type: web
    name: yjs-server
    plan: free
    dockerfilePath: ./server/Dockerfile
    envVars:
      - key: PORT
        value: 80
      - key: HOST
        value: 0.0.0.0
    runtime: docker